name: CI/CD
concurrency: prodstuff

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Linting
        run: echo Linted!
        
  test:
    name: Run Automated Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Testing
        run: echo Tested!
        
  staging:
    name: Deploy to Staging
    concurrency: staging_environment
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: "https://simon.weizman.us"
    steps:
      - name: Deploy to Cloudflare Pages
        uses: Cyb3r-Jak3/actions-cloudflare-pages
        with:
          account: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          project: ${{ secrets.CLOUDFLARE_PROJECT }}
          email: ${{ secrets.CLOUDFLARE_EMAIL }}
          global_token: ${{ secrets.CLOUDFLARE_KEY }}    
    
  production:
    name: Deploy to Production
    concurrency: production_environment
    needs: staging
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: "https://simon.weizman.dev"
    steps:
      - name: Deploy
        run: echo Deploying!
